/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package d14demo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test
    void Test_add_stuff() {
        Library sut = new Library(); // short for system under test
        int firstInt = 1;
        int secondInt = 6;
        assertEquals(7, sut.addStuff(firstInt, secondInt), "addStuff() did not add numbers properly!");
    }

    @Test
    void Test_adding_students() {
        Library sut = new Library();
        sut.listStudents();
    }
}
