/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package d14demo;

import java.util.ArrayList;
import java.util.Arrays;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public int addStuff(int myInt, int myInt2)
    {
      return myInt + myInt2;
    }

    public void listStudents()
    {
      String[] studentsArray = {"Robb", "Josh", "JB", "Ben", "Kevin"};
      String[] testArray = {};
      String[] testArray2 = new String[0];

      ArrayList<Integer> classSizes = new ArrayList<>();
      int class1 = 10;
      int class2 = 20;
      Integer class3 = 3;

      classSizes.add(class1);
      classSizes.add(class2);
      classSizes.add(class3);
      System.out.println("Class sizes: " + classSizes);

      ArrayList<String> students = new ArrayList<>();
      /*students.add("Robb");
      students.add("Josh");
      students.add("JB");
      students.add("Ben");
      students.add("Kevin");*/
      students.addAll(Arrays.asList(studentsArray));
      for (String student : students)
      {
        System.out.println("A student: " + student);
      }
      for (int i = 0; i < students.size(); i++)
      {
        System.out.println("A student again: " + students.get(i));
      }
      students.remove("JB");
      students.remove(0);
      System.out.println("Students are now: " + students);

      ArrayList<Object> whatsInHere = new ArrayList<>();  // BAD! This is really not very Java-like
      whatsInHere.add(3);
      whatsInHere.add("Hello");

      System.out.println("What's in here? " + whatsInHere);

      int anInt = (Integer)whatsInHere.get(0);
    }
}
